---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: alarmpbcfe
  labels:
    app: alarmpbcfe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alarmpbcfe
  template:
    metadata:
      labels:
        app: alarmpbcfe
    spec:
      containers:
        - name: alarmpbcfe
          image: "mini1acr.azurecr.io/alarmpbcfe:latest"
          ports:
            - containerPort: 8080
          